<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsBenchmarkProject>true</IsBenchmarkProject>
		<IsPackable>false</IsPackable>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Arex388.DocuSeal\Arex388.DocuSeal.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\TestData\MockHttpMessageHandler.cs" Link="MockHttpMessageHandler.cs" />
		<None Include="..\TestData\Responses\*.json" Link="Responses\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
		<None Include="..\TestData\Spec\webhook-*.json" Link="Spec\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>